
CREATE DATABASE proyecto_CISMO;

USE proyecto_CISMO;

CREATE TABLE TIENDA (

ID VARCHAR (4) UNIQUE PRIMARY KEY,

NOMBRE VARCHAR (50) NOT NULL,

ESTADO VARCHAR (1) NOT NULL,

CUIDAD VARCHAR (100)

);

-- Tabla EMPLEADO

CREATE TABLE EMPLEADO (

ID INT PRIMARY KEY AUTO_INCREMENT,

CUIL VARCHAR(20) NOT NULL,

APENOM VARCHAR(60) NOT NULL,

LEGAJOREAL INT  NOT NULL,

ESTADO VARCHAR(1)

);

-- Tabla empleados de tiendas

CREATE TABLE EMPLEADO_TIENDA (

LEGAJO INT  NOT NULL PRIMARY KEY ,

IDTIENDA INT,

ESTADO VARCHAR (1)

);

-- Tabla FACTURACION CABECERA

CREATE TABLE FACTURACIONCAB (

ID INT PRIMARY KEY AUTO_INCREMENT,

IDTIENDA VARCHAR(4),

FECHAVENTA DATE,

TIPOCOMPROBANTE VARCHAR (3),

CAJA INT (3) ,

LEGAJO INT NOT NULL,

NROCOMPROBANTE VARCHAR (20),

IMPORTE DECIMAL (14,4)

);

-- Tabla FACTURACION DETALLE

CREATE TABLE FACTURACIONDET (

IDFACTURA INT PRIMARY KEY,

DESCRIPCION VARCHAR (200),

IMPORTE DECIMAL (14,4)

);

-- Tabla MEDIOS DE PAGO

CREATE TABLE MEDIODEPAGO (

IDMEDIODEPAGO INT PRIMARY KEY AUTO_INCREMENT,

IDTIENDA VARCHAR(4),

FHVENTA DATE,

TIPOCOMPROBANTE VARCHAR (3),

NROCOMPROBATE VARCHAR (50),

LEGAJO INT NOT NULL,

VARIEDAD INT,

IMPORTE decimal (14,4)

);

-- Tabla VARIEDADES (FORMA DE PAGO)

CREATE TABLE VARIEDADES (

ID INT PRIMARY KEY AUTO_INCREMENT,

NOMBRE VARCHAR (60),

ESTADO VARCHAR (1)

);

-- tabla tipo comprobante

CREATE TABLE TIPOCOMPROBANTE (

ID VARCHAR (3) PRIMARY KEY,

NOMBRE VARCHAR (60),

ESTADO VARCHAR (1)

);

-- FACTURACION CABECERA

ALTER TABLE FACTURACIONCAB
ADD CONSTRAINT FK_FACTURACIONDET_FACTURACIONCAB
FOREIGN KEY (ID) REFERENCES FACTURACIONDET (IDFACTURA);

ALTER TABLE FACTURACIONCAB
ADD CONSTRAINT FK_TIENDA_FACTURACIONCAB
FOREIGN KEY (IDTIENDA) REFERENCES TIENDA (ID);


ALTER TABLE FACTURACIONCAB
ADD CONSTRAINT FK__TIPOCOMPROBANTE_FACTURACIONCAB
FOREIGN KEY (TIPOCOMPROBANTE) REFERENCES TIPOCOMPROBANTE (ID);

ALTER TABLE FACTURACIONCAB
ADD CONSTRAINT FK__EMP_FACTURACIONCAB
FOREIGN KEY (LEGAJO) REFERENCES EMPLEADO_TIENDA (LEGAJO);


ALTER TABLE EMPLEADO
ADD CONSTRAINT FK_EMPLEADO_TIENDA
FOREIGN KEY (ID) REFERENCES EMPLEADO_TIENDA (LEGAJO);

ALTER TABLE MEDIODEPAGO
ADD CONSTRAINT FK_MEDIODEPAGO_VARIEADES
FOREIGN KEY (VARIEDAD) REFERENCES VARIEDADES (ID);

ALTER TABLE MEDIODEPAGO
ADD CONSTRAINT FK__EMP_MEDIODEPAGO
FOREIGN KEY (LEGAJO) REFERENCES EMPLEADO_TIENDA (LEGAJO);

ALTER TABLE MEDIODEPAGO
ADD CONSTRAINT FK__TIPOCOMPROBANTE_MEDIODEPAGO
FOREIGN KEY (TIPOCOMPROBANTE) REFERENCES TIPOCOMPROBANTE (ID);

ALTER TABLE MEDIODEPAGO
ADD CONSTRAINT FK_TIENDA_MEDIODEPAGO
FOREIGN KEY (IDTIENDA) REFERENCES TIENDA (ID);
